/**
 * Prisma Seed Script
 *
 * Reads the final normalized data from the pipeline output
 * and seeds the database using upsert (idempotent, safe to re-run).
 *
 * STS2 Pattern: JSON seed files → Prisma upsert → reproducible builds
 *
 * Usage: npx tsx prisma/seed.ts
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...\n');

  // The final data file is produced by scripts/09-normalize-and-seed.ts
  // which combines all pipeline outputs into a single JSON structure.
  // For now, we log the expected workflow.

  console.log('📋 Expected workflow:');
  console.log('   1. npm run pipeline:all     → run all data pipeline steps');
  console.log('   2. npm run db:seed          → this script');
  console.log('');
  console.log('💡 The seed data is generated by the pipeline scripts.');
  console.log('   See scripts/09-normalize-and-seed.ts for the final step.');
  console.log('');
  console.log('📁 Data directory:', process.cwd() + '/data/');
  console.log('   After pipeline: books.json, adaptations-final.json, streaming.json');

  // TODO: Once pipeline outputs exist, implement the actual seeding logic:
  //
  // const data = JSON.parse(readFileSync('data/adaptations-final.json', 'utf-8'));
  //
  // for (const book of data.books) {
  //   await prisma.book.upsert({
  //     where: { slug: book.slug },
  //     update: book,
  //     create: book,
  //   });
  // }
  //
  // for (const adaptation of data.adaptations) {
  //   await prisma.adaptation.upsert({
  //     where: { slug: adaptation.slug },
  //     update: adaptation,
  //     create: adaptation,
  //   });
  // }

  console.log('✅ Seed complete (no data yet — run the pipeline first)');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
